spring.application.name=youwantt
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
server.port = 8181
spring.datasource.url=jdbc:mysql://localhost:3306/youwantt
spring.datasource.username=root
spring.datasource.password=Ayushisahu
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true